- path: /releases/name=cf-mysql/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-mysql-36.14.0-ubuntu-trusty-3586.16-20180524-190215-999453655.tgz
- path: /releases/name=cf-mysql/version
  type: replace
  value: 36.14.0
- path: /releases/name=cf-mysql/sha1
  type: replace
  value: bb7a51fc26593b3192bd2087c53b467ee5df3f1b
- path: /releases/name=capi/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/capi-1.59.0-ubuntu-trusty-3586.16-20180530-170752-58003876.tgz
- path: /releases/name=capi/version
  type: replace
  value: 1.59.0
- path: /releases/name=capi/sha1
  type: replace
  value: ac5eabdd86aa1a085bf210e6ac284e044376f1fd
- path: /releases/name=binary-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/binary-buildpack-1.0.18-ubuntu-trusty-3586.16-20180524-182708-593429376.tgz
- path: /releases/name=binary-buildpack/version
  type: replace
  value: 1.0.18
- path: /releases/name=binary-buildpack/sha1
  type: replace
  value: b08758694708bd1c26ecd159108fb9efb091f44b
- path: /releases/name=cf-networking/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-networking-1.13.0-ubuntu-trusty-3586.16-20180524-183010-908745936.tgz
- path: /releases/name=cf-networking/version
  type: replace
  value: 1.13.0
- path: /releases/name=cf-networking/sha1
  type: replace
  value: 36f9ee7021fdd9de39a2422541d9fb8c46cbdd81
- path: /releases/name=uaa/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/uaa-59-ubuntu-trusty-3586.16-20180524-183116-73781225.tgz
- path: /releases/name=uaa/version
  type: replace
  value: "59"
- path: /releases/name=uaa/sha1
  type: replace
  value: 5dd7c3dc918b3d804e5f7bcda92b7e139dedde9d
- path: /releases/name=nats/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/nats-24-ubuntu-trusty-3586.16-20180524-182832-650335514.tgz
- path: /releases/name=nats/version
  type: replace
  value: "24"
- path: /releases/name=nats/sha1
  type: replace
  value: 1951d29950f579fe422a196f25232e0f4ea02315
- path: /releases/name=diego/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/diego-2.8.0-ubuntu-trusty-3586.16-20180528-193933-49120377.tgz
- path: /releases/name=diego/version
  type: replace
  value: 2.8.0
- path: /releases/name=diego/sha1
  type: replace
  value: 899946fa89cdf607fdb842a3f12d48eb178dda5a
- path: /releases/name=routing/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/routing-0.178.0-ubuntu-trusty-3586.16-20180524-183004-78764697.tgz
- path: /releases/name=routing/version
  type: replace
  value: 0.178.0
- path: /releases/name=routing/sha1
  type: replace
  value: c86bcd6880a9679fbfba6892af80b1daeeb8a2bc
- path: /releases/name=consul/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/consul-193-ubuntu-trusty-3586.16-20180530-001128-973028038.tgz
- path: /releases/name=consul/version
  type: replace
  value: "193"
- path: /releases/name=consul/sha1
  type: replace
  value: 77f0e8025bf1962b7c1cdcb472af063a9cf50230
- path: /releases/name=cflinuxfs2/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cflinuxfs2-1.211.0-ubuntu-trusty-3586.16-20180528-110655-450559645.tgz
- path: /releases/name=cflinuxfs2/version
  type: replace
  value: 1.211.0
- path: /releases/name=cflinuxfs2/sha1
  type: replace
  value: 1b71f02e29522ab199c7a43346f1109a045f4908
- path: /releases/name=garden-runc/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/garden-runc-1.13.3-ubuntu-trusty-3586.16-20180524-183454-245084631.tgz
- path: /releases/name=garden-runc/version
  type: replace
  value: 1.13.3
- path: /releases/name=garden-runc/sha1
  type: replace
  value: 82666f04fda85c3bcb9a1afc6f2436b444f916ec
- path: /releases/name=loggregator/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/loggregator-102.1-ubuntu-trusty-3586.16-20180524-182952-082010903.tgz
- path: /releases/name=loggregator/version
  type: replace
  value: "102.1"
- path: /releases/name=loggregator/sha1
  type: replace
  value: 4c95a070489568539d358d8e9f21f9a65a6beb80
- path: /releases/name=go-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/go-buildpack-1.8.21-ubuntu-trusty-3586.16-20180524-182635-052408468.tgz
- path: /releases/name=go-buildpack/version
  type: replace
  value: 1.8.21
- path: /releases/name=go-buildpack/sha1
  type: replace
  value: dd710a621fda81e5dea03be69782302bc9df5e9b
- path: /releases/name=php-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/php-buildpack-4.3.54-ubuntu-trusty-3586.16-20180524-182634-515075615.tgz
- path: /releases/name=php-buildpack/version
  type: replace
  value: 4.3.54
- path: /releases/name=php-buildpack/sha1
  type: replace
  value: b640c0018ee693b8143899b1c36d3262e7bad7e6
- path: /releases/name=cf-smoke-tests/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-smoke-tests-40.0.5-ubuntu-trusty-3586.16-20180524-182850-550494257.tgz
- path: /releases/name=cf-smoke-tests/version
  type: replace
  value: 40.0.5
- path: /releases/name=cf-smoke-tests/sha1
  type: replace
  value: f4680d0b1a8982b0970592c2a344052f310aee2e
- path: /releases/name=java-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/java-buildpack-4.12-ubuntu-trusty-3586.16-20180524-182706-666063212.tgz
- path: /releases/name=java-buildpack/version
  type: replace
  value: "4.12"
- path: /releases/name=java-buildpack/sha1
  type: replace
  value: db6a65958517524a85c9099993c3bc920206ef16
- path: /releases/name=ruby-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/ruby-buildpack-1.7.18-ubuntu-trusty-3586.16-20180524-182707-844429921.tgz
- path: /releases/name=ruby-buildpack/version
  type: replace
  value: 1.7.18
- path: /releases/name=ruby-buildpack/sha1
  type: replace
  value: 2fbe7d0de041637e4df742ea71d55bba3836eeac
- path: /releases/name=statsd-injector/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/statsd-injector-1.3.0-ubuntu-trusty-3586.16-20180524-182905-119368785.tgz
- path: /releases/name=statsd-injector/version
  type: replace
  value: 1.3.0
- path: /releases/name=statsd-injector/sha1
  type: replace
  value: 8db13ba0595eabfe27e71118f561ce3d454dd49e
- path: /releases/name=nodejs-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/nodejs-buildpack-1.6.23-ubuntu-trusty-3586.16-20180524-182707-889306973.tgz
- path: /releases/name=nodejs-buildpack/version
  type: replace
  value: 1.6.23
- path: /releases/name=nodejs-buildpack/sha1
  type: replace
  value: 9812ee7cb67ae149513bfa858961b33d8c211d19
- path: /releases/name=python-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/python-buildpack-1.6.15-ubuntu-trusty-3586.16-20180524-182634-463579654.tgz
- path: /releases/name=python-buildpack/version
  type: replace
  value: 1.6.15
- path: /releases/name=python-buildpack/sha1
  type: replace
  value: 4f6e8b5e6b85ee721e4e4aeb14e66600e6453b1c
- path: /releases/name=staticfile-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/staticfile-buildpack-1.4.27-ubuntu-trusty-3586.16-20180524-182711-495459916.tgz
- path: /releases/name=staticfile-buildpack/version
  type: replace
  value: 1.4.27
- path: /releases/name=staticfile-buildpack/sha1
  type: replace
  value: 6e550d34e1dbf5dd178231c9b5b6bd9435875560
- path: /releases/name=dotnet-core-buildpack/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/dotnet-core-buildpack-2.0.6-ubuntu-trusty-3586.16-20180524-182709-193762236.tgz
- path: /releases/name=dotnet-core-buildpack/version
  type: replace
  value: 2.0.6
- path: /releases/name=dotnet-core-buildpack/sha1
  type: replace
  value: 921f21ec989f0e6e61af62ad77b31f9f3f969dbc
- path: /releases/name=cf-syslog-drain/url
  type: replace
  value: https://storage.googleapis.com/cf-deployment-compiled-releases/cf-syslog-drain-6.5-ubuntu-trusty-3586.16-20180524-182959-396975204.tgz
- path: /releases/name=cf-syslog-drain/version
  type: replace
  value: "6.5"
- path: /releases/name=cf-syslog-drain/sha1
  type: replace
  value: 549a703a646000125fe34cdd018b8d66375ad5b4
- path: /releases/name=capi/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-mysql/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=binary-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-networking/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-smoke-tests/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-syslog-drain/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cflinuxfs2/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=consul/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=diego/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=dotnet-core-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=garden-runc/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=go-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=java-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=loggregator/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=nats/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=nodejs-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=php-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=python-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=routing/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=ruby-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=cf-mysql/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=staticfile-buildpack/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=statsd-injector/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
- path: /releases/name=uaa/stemcell?
  type: replace
  value:
    os: ubuntu-trusty
    version: "3586.16"
